// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtbAom9ciyCKoELQvYscVxwuiy-qoI22k',
    appId: '1:691131337162:web:99831c44d996cdfc16e733',
    messagingSenderId: '691131337162',
    projectId: 'inventory-manager-app-fc22c',
    authDomain: 'inventory-manager-app-fc22c.firebaseapp.com',
    storageBucket: 'inventory-manager-app-fc22c.firebasestorage.app',
    measurementId: 'G-8GN52S87ZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDBuJUvqYeS05lyXe6ximyhtlM42PGMfI',
    appId: '1:691131337162:android:ec9145a7f1d123e316e733',
    messagingSenderId: '691131337162',
    projectId: 'inventory-manager-app-fc22c',
    storageBucket: 'inventory-manager-app-fc22c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIIwodc9YWQJ-8-DgOVouYqqHn2sYDx4g',
    appId: '1:691131337162:ios:0f8355536d8c8a3116e733',
    messagingSenderId: '691131337162',
    projectId: 'inventory-manager-app-fc22c',
    storageBucket: 'inventory-manager-app-fc22c.firebasestorage.app',
    iosBundleId: 'com.example.inventryManagerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIIwodc9YWQJ-8-DgOVouYqqHn2sYDx4g',
    appId: '1:691131337162:ios:0f8355536d8c8a3116e733',
    messagingSenderId: '691131337162',
    projectId: 'inventory-manager-app-fc22c',
    storageBucket: 'inventory-manager-app-fc22c.firebasestorage.app',
    iosBundleId: 'com.example.inventryManagerApp',
  );
}
